name: Build and deploy WAR app to Azure Web App - seniorcarejava

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: |
          cd crud-senior-care
          mvn clean install -Dfile.encoding=UTF-8

      - name: Verify WAR file exists
        run: |
          if [ ! -f crud-senior-care/target/*.war ]; then
            echo "WAR file not found!"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: crud-senior-care/target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EC5E8ACBC8A4559A45042B39325
