name: Build and deploy JAR app to Azure Web App - spring-boot-senior-care

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: |
          cd spring-boot-senior-care
          mvn clean install -Dfile.encoding=UTF-8
          ls -la target

      - name: Verify JAR file
        run: |
          echo "Listing target directory contents:"
          ls -la spring-boot-senior-care/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: spring-boot-senior-care/target/spring-boot-senior-care-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3EC5E8ACBC8A4559A45042B393251C19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8061BE698BFA4CEEAD532EADD396ECD8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61B2E56426594FC18359596134DECD5A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-boot-senior-care'
          slot-name: 'Production'
          package: spring-boot-senior-care/target/spring-boot-senior-care-0.0.1-SNAPSHOT.jar
